### PR TITLE
update .gitignore, add optional command line args

### PR DESCRIPTION
**Pull request by anytarseir67**

### CODE REVIEW

**Comment by ofthegoats** [comment]
Looks good, just match the formatting with the rest of the file: position of \* on argv and if/else before merging

**Comment by anytarseir67** [comment]
what's wrong with the formatting of the if/else ?

**Comment by ofthegoats** [comment]
`else` should be on the same line as the closing brace for `if`, so `} else {`

**Comment by anytarseir67** [comment]
> `else` should be on the same line as the closing brace for `if`, so `} else {`

done

**Comment by ofthegoats** [comment]
Nice, thanks!

**Pull request merged**
